In [1]:
!pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 831.9 kB/s eta 0:00:15
   -- ------------------------------------- 0.8/12.8 MB 826.9 kB/s eta 0:00:15
   -- ------------------------------------- 0.8/12.8 MB 826.9 kB/s eta 0:00:15
   --- ------------------------------------ 1.0/12.8 MB 813.6 kB/s eta 0:00:15
   ---- ----------------------------------- 1.3/12.8 MB 818.8 kB/s eta 0:00:15
   ---- ----------------------------------- 1.3/12.8 MB 818.8 kB/s eta 0:00:15
   ---- ----------------------------------- 1.6/12.8 MB 739.5 kB/s eta 0:00:16
   ---- ----------------------------------- 1.6/12.8 MB 739.5 kB/s eta 0:00:16
   ---- ----------------------------------- 1.6/12.8 MB 739.5 kB/s eta 0:00:16
   ---- -

In [2]:
import numpy as np


In [3]:
arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


In [6]:
v1 = np.array([1,2,3])
m1 = np.matrix([1, 2], [3, 4], [5, 6])
print(m1)
print(v1)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [7]:
import numpy as np

v1 = np.array([1, 2, 3])
m1 = np.matrix([[1, 2], [3, 4], [5, 6]])

print("Matrix m1:")
print(m1)

print("Vector v1:")
print(v1)


Matrix m1:
[[1 2]
 [3 4]
 [5 6]]
Vector v1:
[1 2 3]


In [8]:
#evenly separate the values
n = np.linspace(0, 1, 100)
print(n)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898